# Generated by Django 2.2 on 2020-07-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200718_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
